{
    "event":"occurred",
    "message":"[Crywolf/test] RuntimeError - oops",
    "fault":{
        "id":3151009,
        "project_id":1717,
        "klass":"RuntimeError",
        "component":null,
        "action":null,
        "environment":"development",
        "resolved":true,
        "ignored":false,
        "created_at":"2014-01-08T18:55:48Z",
        "comments_count":1,
        "message":"oops",
        "notices_count":9,
        "last_notice_at":"2014-01-08T19:02:21Z"
    }
}